version: '3.3'
services:
    influxdb:
        container_name: influxdb
        ports:
            - '8086:8086'
        volumes:
            - ./influxdb:/var/lib/influxdb'
            - ./influxdb:/var/lib/influxdb
            - ./influxdb:/etc/influxdb
        environment:
            - TZ=" America/Argentina/Buenos_Aires"
            - DOCKER_INFLUXDB_INIT_MODE=upgrade
            - DOCKER_INFLUXDB_INIT_USERNAME=iot4
            - DOCKER_INFLUXDB_INIT_PASSWORD=iot4pass
            - DOCKER_INFLUXDB_INIT_ORG=iot4
            - DOCKER_INFLUXDB_INIT_BUCKET=iot4
        image: influxdb:1.8
        restart: always
    node-red:
        container_name: nodered
        ports:
            - '1880:1880'
        volumes:
            - ../nodered:/data'
        container_name: mynodered
        image: nodered/node-red
        restart: always
    mosquitto:
        container_name: mqtt
        image: eclipse-mosquitto
        volumes:
           - ./mosquitto/config/:/mosquitto/config
           - ./mosquitto/data/:/mosquitto/data
           - ./mosquitto/log/:/mosquitto/log
        ports:
          - 1883:1883
          - 9001:9001
        restart: always
    grafana:
       container_name: grafana
       image: grafana/grafana
       ports:
          - '3000:3000'
       volumes:
           - ./grafana/:/etc/grafana/provisioning
           - ./grafana/:/var/lib/grafana/dashboards
       restart: always
    telegraf:
       container_name: telegraf
       image: telegraf:1.18-alpine
       volumes:
           - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:rw
       depends_on:
           - influxdb
       links:
           - influxdb
       ports:
           - 8125:8125
       restart: always
